### ISSUE TITLE
Questions: How is this library maintained? ...

### ISSUE THREAD

**Issue by jraska** [felipecsl/walkman#26]
Hello,

I was about to write something similar record/replay for OkHttp and I found your library, which I'm quite happy about, because I don't want to reinvent the wheel and the tool looks great, however I have few questions.

1. Is this something Airbnb uses internally? It is not on GitHub under the Airbnb organization, has many commits and contributions so I'm curious why.
2. Is this maintained here or is it just a mirror for Airbnb tool elsewhere? This repo doesn't look much active so I'm curious if Airbnb maintains it somewhere else.

Thank you for answer.

Josef

**Comment by felipecsl** [comment]
Hello Josef, thanks for asking!

1. Yes, we're currently using Walkman internally at Airbnb and it's been working out great for us! It has a lot of commits because it was forked out of https://github.com/betamaxteam/betamax 😄 
2. It is currently maintained here, but we're working on moving it to the official Airbnb org and making it more "official". It's still not considered officially Airbnb open source but it will soon. Once we're ready, we'll just move the repository over!

Cheers,
Felipe

**Comment by jraska** [comment]
Sounds good, thank you for answers!
